### ISSUE TITLE
running metacmp.py is wrong

### ISSUE THREAD

**Issue by Keyanchu** [minoh0201/metacompare#9]
I run ' ./metacmp.py'. The result is wrong. 
The detail is ' Traceback (most recent call last):
  File "./metacmp.py", line 20, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio''

**Comment by wenrenqiao** [comment]
> I run ' ./metacmp.py'. The result is wrong. The detail is ' Traceback (most recent call last): File "./metacmp.py", line 20, in from Bio import SeqIO ModuleNotFoundError: No module named 'Bio''

I get the same error，'python ./metacmp.py' can solve it
